<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    
    <parent>
        <groupId>io.gdcc</groupId>
        <artifactId>parent</artifactId>
        <version>0.15.2</version>
    </parent>
    
    <groupId>io.gdcc.spi</groupId>
    <artifactId>parent</artifactId>
    <!-- For now, keep all the module versions in lockstep. Can be diversified later. -->
    <version>2.1.0-SNAPSHOT</version>
    <packaging>pom</packaging>
    
    <name>Dataverse SPI Plugin API</name>
    <url>https://dataverse.org</url>
    <modules>
        <module>api</module>
        <module>core</module>
        <module>export</module>
        <module>meta</module>
    </modules>
    <description>
        A package to create out-of-tree Java code for Dataverse Software. Plugin projects can use this package
        as an API dependency just like Jakarta EE APIs if they want to create external plugins. These will be loaded
        at runtime of a Dataverse installation using SPI. See also https://guides.dataverse.org/en/latest/developers
        for more information.
    </description>
    
    <developers>
        <developer>
            <name>Dataverse Core Team</name>
            <email>support@dataverse.org</email>
        </developer>
    </developers>
    
    <licenses>
        <license>
            <name>${project.license.name}</name>
            <url>${project.license.url}</url>
            <distribution>repo</distribution>
        </license>
    </licenses>
    
    <scm>
        <url>https://github.com/gdcc/dataverse-spi</url>
    </scm>
    
    <properties>
        <jdk.version>17</jdk.version>
        <project.github.org>gdcc</project.github.org>
        <project.github.repo>dataverse-spi</project.github.repo>
        <project.license.name>Apache License, Version 2.0</project.license.name>
        <project.license.url>https://www.apache.org/licenses/LICENSE-2.0.txt</project.license.url>
        <docs.site.base>/</docs.site.base>
    </properties>
    
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>io.gdcc.spi</groupId>
                <artifactId>meta</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>io.gdcc.spi</groupId>
                <artifactId>core</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>io.gdcc.spi</groupId>
                <artifactId>export</artifactId>
                <version>${project.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>
    
    <dependencies>
        <!-- TESTING -->
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>
    
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-site-plugin</artifactId>
                <dependencies>
                    <dependency>
                        <groupId>org.sentrysoftware.maven</groupId>
                        <artifactId>maven-skin-tools</artifactId>
                        <version>1.7.00</version>
                    </dependency>
                </dependencies>
            </plugin>
        </plugins>
    </build>
    
    <reporting>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-javadoc-plugin</artifactId>
                <reportSets>
                    <reportSet>
                        <id>aggregate-javadocs</id>
                        <!-- inherited=false means children do not do the same thing individually -->
                        <inherited>false</inherited>
                        <reports>
                            <report>aggregate</report>
                        </reports>
                    </reportSet>
                </reportSets>
                <configuration>
                    <!-- Note: configuration here must be repeated, as one contained in <build> is not crossing over! -->
                    <show>protected</show>
                    <source>${jdk.version}</source>
                    <detectLinks>true</detectLinks>
                    <doclint>${javadoc.lint}</doclint>
                    <failOnWarnings>false</failOnWarnings>
                    <quiet>true</quiet>
                    <!-- Beneficial for bit-equal builds on successive builds -->
                    <notimestamp>true</notimestamp>
                    <!-- Add modern tags not yet included by default. https://nipafx.dev/javadoc-tags-apiNote-implSpec-implNote -->
                    <tags>
                        <tag><name>apiNote</name><placement>a</placement><head>API Note:</head></tag>
                        <tag><name>implSpec</name><placement>a</placement><head>Implementation Requirements:</head></tag>
                        <tag><name>implNote</name><placement>a</placement><head>Implementation Note:</head></tag>
                    </tags>
                    
                    <doctitle>Dataverse SPI Plugin API Reference</doctitle>
                    <windowtitle>Dataverse SPI Plugin API Reference</windowtitle>
                    <addStylesheets>
                        <addStylesheet>custom.css</addStylesheet>
                    </addStylesheets>
                    <!-- Create a banner on top of every page allowing to return to main docs page   -->
                    <top><![CDATA[
                        <div class="top-nav-backlink">
                            <a href="${docs.site.base}index.html">← Back to Dataverse SPI Plugin API homepage</a>
                        </div>
                    ]]></top>
                    <bottom><![CDATA[
                        <div>
                            Version ${project.version} -&nbsp;
                            Copyright by ${project.organization.name} -&nbsp;
                            Licensed under <a href="${project.license.url}" target="_blank">${project.license.name}</a> |&nbsp;
                            <a href="${docs.site.base}index.html">Dataverse SPI Plugin API</a> |&nbsp;
                            <a href="https://dataverse.org" target="_blank">The Dataverse Project</a>
                        </div>
                    ]]></bottom>
                </configuration>
            </plugin>
            
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-project-info-reports-plugin</artifactId>
                <reportSets>
                    <reportSet>
                        <id>root-project-info</id>
                        <!-- inherited=false means children do not do the same thing individually -->
                        <inherited>false</inherited>
                        <reports>
                            <report>team</report>
                        </reports>
                    </reportSet>
                </reportSets>
            </plugin>
        </plugins>
    </reporting>
    
</project>
